### ISSUE TITLE
Working Search Functionality

### ISSUE THREAD

**Issue by Noah-droid** [Noah-droid/colobyv1.0#58]
We need to implement a search functionality whereby users can search for anything related that they want

**Comment by VidyaYadavv1519** [comment]
hii, if this issue is still available,
can you assign me ??

**Comment by Noah-droid** [comment]
> hii, if this issue is still available,
> 
> can you assign me ??

Yeah no problem. You can pick up the issue. I would also love to know how you found out about us

**Comment by VidyaYadavv1519** [comment]
i was just going through the issues and found this issue 
thankyou for assigning

**Comment by VidyaYadavv1519** [comment]
there are already so many issues in setting up the project only.

**Comment by VidyaYadavv1519** [comment]
hello, i just wanted to know that there are two apps accounts and cowork in which app do you want this functionality ??

**Comment by Noah-droid** [comment]
Hi there, you can use the cowork app for this

**Comment by VidyaYadavv1519** [comment]
can you elaborate more like for which model do you want this search functionality ??

**Comment by Noah-droid** [comment]
> can you elaborate more like for which model do you want this search functionality ??

the room models. Here, users can search for various rooms that are made public
