### ISSUE TITLE
Work on Notifications

### ISSUE THREAD

**Issue by Noah-droid** [Noah-droid/colobyv1.0#59]
Setup In-App notification, mail notification for every major events done by the user

**Comment by Noah-droid** [comment]
Already installed django-notifications-hq 1.8.3 and django-notifications-rest, just need some more time with it

**Comment by shadow-ryu** [comment]
I'm interested in tackling this task.

**Comment by Noah-droid** [comment]
Go ahead @shadow-ryu

**Comment by shadow-ryu** [comment]
When attempting to run the application locally, I encounter an error in the `settings.py` file, specifically related to installed apps and other configurations.

**Comment by Noah-droid** [comment]
Can you type in what error it is??

**Comment by shadow-ryu** [comment]
`  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework'`

 even though  I have run pip command

**Comment by Noah-droid** [comment]
Does this happen when you run server?

**Comment by Noah-droid** [comment]
> Does this happen when you run server?

If yes, can you try to narrow it down to where it's being imported? Probably there was some typos or something else

**Comment by shadow-ryu** [comment]
okay

**Comment by shadow-ryu** [comment]
@Noah-droid  still  getting packages  not found issue

**Comment by shadow-ryu** [comment]
@Noah-droid  Sorry,  but I won't be able to address this matter at the moment as I'm encountering difficulties setting it up on my local machine. I'm currently engrossed in another task. Consequently, I've decided to unassign myself from this issue

**Comment by Noah-droid** [comment]
Okay no problem, Good luck man 💪
