### ISSUE TITLE
Frontend Issues

### ISSUE THREAD

**Issue by Noah-droid** [Noah-droid/colobyv1.0#8]
- Display frontend authentication page using react

- Display landing page using react

- Display dashboard using react

- Work on features UI

**Comment by Mayhoral8** [comment]
Alright, is there a branding scheme to follow? i.e colours, fonts e.t.c

**Comment by Noah-droid** [comment]
Actually, we are to follow the color of the logo used as DP on the WhatsApp group, which is basically white and blue

**Comment by Mayhoral8** [comment]
Alright
